[phases.setup]
apts = ["python3", "make", "g++", "gcc"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "npm_config_build_from_source=true pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
